# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Surf' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Surf
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'Surf-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SurfTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Surf-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Surf-tvOS

end
